### ISSUE TITLE
Problems with using Linux with the pack

### ISSUE THREAD

**Issue by samip5** [MinecraftModDevelopment/New-MMD-Public-Pack#54] opened 2018-04-15 13:56 UTC
Alright, so let me begin with saying that there's multiple problems.
Main problem is the wrong mod version.

![The screenshot](http://i.imgur.com/X1mjwH6.png)

Logs can be found at: https://www.dropbox.com/sh/xnxmcmdmmqtl769/AAD8p_FKjpZ0n66ch95zTGQja?dl=0

- [x] Wrong mod version that can be grabbed from courseforge.
- [ ] Hard to download, due to lack of Twitch app for Linux
- [ ] Textures missing

**Comment by ProxyNeko** [comment] 2018-04-15 14:10
This is an error the mod author has caused by deleting his older maybe broken mod versions and then it breaks mod packs/servers but there's nothing I can do about that until DILUV has released.

Nothing we can do about the pack being hard to download this second but I plan on uploading the releases to GitHub once final releases are made to make it easier for us Linux users :) but again I'm waiting on DILUV as that is meant to be the Curse rival with Linux support by default.

As for the missing textures, I can't fix those either that is for the mod developer to fix so, in this case, it would be TehNut who can be found on the BloodMagic GitHub repo or in Discord but the next version should have a bunch of missing texture fixes hopefully.

**Comment by samip5** [comment] 2018-04-15 14:34
What's DILUV?

Glad to hear that there are plans to make it easier for Linux users. :+1: 

The missing textures are from multiple mods, so is TehNut the developer for all of them? As these are the mods with missing textures, per the log: Chisel, RfTools, NuclearCraft, SimpleJetPacks, Buildcraft and ImmersiveEngineering.

**Comment by ProxyNeko** [comment] 2018-04-15 14:58
Look in Discord on the server there should be a channel with the same name it's a wip still but they can tell you more in there.

And I'm not sure who the authors of the rest of those are but Blood Magic is the only one I think TehNut works on but Blood Magic is still being worked on

**Comment by ProxyNeko** [comment] 2018-04-20 13:13
Going to close this as textures are not something we can fix the mod devs will do that and over time it will be applied in releases. An easier way to download the pack would be multiMC for now but I do have plans to make it easier for myself as well so will make that public later in the final release.

**Closed by ProxyNeko** 2018-04-20 13:13 UTC
Labels: bug
